GET http://localhost:5090/games

###
GET http://localhost:5090/games/2

###
 POST http://localhost:5090/games
 Content-Type: application/json

 {
   "name": "Super Mario Bros. Wonder",
   "genreId": 3,
   "price": 100,
   "releaseDate": "1991-10-20"
 }

###
 PUT http://localhost:5090/games/2
 Content-Type: application/json

 {
   "name": "Super Mario Bros. Wonder",
   "genreId": 3,
   "price": 19.99,
   "releaseDate": "1991-10-20"
 }

###
 DELETE http://localhost:5090/games/18

###
 GET http://localhost:5090/genres

### Upload image to game 1
POST http://localhost:5090/games/19/image
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="cover.png"
Content-Type: image/png

< C:\Users\User\Downloads\MarioBrosWonder.jpg
--MyBoundary--

